package com.retrovault.settings

import android.content.Context
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.File

@Serializable
data class GameDbEntry(
    val serial: String,
    val flags: List<String> = emptyList(),
    val settings: Map<String, String> = emptyMap(),
)

@Serializable
private data class GameDbSnapshot(
    val schemaVersion: Int = 1,
    val source: String = "",
    val entryCount: Int = 0,
    val entries: List<GameDbEntry> = emptyList(),
)

/**
 * The GameDB layer's data source: the baked APK snapshot (`assets/gamedb/snapshot.json`,
 * generated by `tools/gamedb-import`), overridable by a newer cached copy downloaded from the
 * public storage snapshot (refresh wiring arrives with P13's compat surfacing).
 *
 * Note the two levels of compat data:
 * - PPSSPP's own `compat.ini` ships via CoreAssets and is applied by the CORE per-serial
 *   (all 72 engine flag sections) — no app plumbing needed.
 * - This class exposes the same flags to the APP (game-page surfacing, auto-save gating)
 *   plus Pulsar-level setting overrides curated in the `gamedb_entries.settings` column.
 */
object GameDb {

    const val REMOTE_SNAPSHOT_URL =
        "https://mxasjicdkryaqugrccdo.supabase.co/storage/v1/object/public/gamedb/latest.json"

    private val json = Json { ignoreUnknownKeys = true }

    @Volatile
    private var cache: Map<String, GameDbEntry>? = null

    private val serialPattern = Regex("^[A-Z]{2,4}-[0-9]{3,6}$")

    fun load(context: Context): Map<String, GameDbEntry> {
        cache?.let { return it }
        synchronized(this) {
            cache?.let { return it }
            val cached = File(context.filesDir, "gamedb-cache.json")
            val text = runCatching {
                if (cached.isFile && cached.length() > 0) cached.readText()
                else context.assets.open("gamedb/snapshot.json").bufferedReader().readText()
            }.getOrNull()
            val parsed = text?.let {
                runCatching { json.decodeFromString<GameDbSnapshot>(it) }.getOrNull()
            }
            val map = parsed?.entries?.associateBy { it.serial } ?: emptyMap()
            cache = map
            return map
        }
    }

    fun entryFor(context: Context, serial: String?): GameDbEntry? {
        val s = serial?.uppercase() ?: return null
        if (!serialPattern.matches(s)) return null // homebrew fake IDs etc.
        return load(context)[s]
    }

    fun flagsFor(context: Context, serial: String?): List<String> =
        entryFor(context, serial)?.flags ?: emptyList()

    /** Pulsar setting overrides for this serial — the resolver's GAMEDB layer. */
    fun settingsFor(context: Context, serial: String?): Map<String, String> =
        entryFor(context, serial)?.settings ?: emptyMap()

    fun hasFlag(context: Context, serial: String?, flag: String): Boolean =
        flagsFor(context, serial).contains(flag)

    /** Test hook / refresh hook: drop the in-memory cache so the next load re-reads disk. */
    fun invalidate() {
        cache = null
    }
}
